# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- mas
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'
  - task: DotNetCoreCLI@2
    displayName: 'Unit tests task'
    inputs:
      command: 'test'
      arguments: '--configuration $(buildConfiguration)'
      #configuration: ' $(buildConfiguration)'ter



variables:
  buildConfiguration: 'Release'
  solution: 'Proto.sln'
  packagejson: 'Proto.Web/client-app'

jobs:
- job: dotnet
  pool: 'Default'
  steps:
  - checkout: self
    clean: 'false'
      projects: '$(solution)'
      testRunTitle: 'Unit tests'
- job: angular
  #dependsOn: dotnet
  pool: 'Default'
  steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: 'custom'
      workingDir: '$(packagejson)'
      customCommand: 'install'
  - task: Npm@1
    displayName: 'npm build'
    inputs:
      command: 'custom'
      workingDir: '$(packagejson)'
      customCommand: 'run build'
  - task: Npm@1
    displayName: 'npm test'
    inputs:
      #clean: false
      command: 'custom'
      workingDir: '$(packagejson)'
      customCommand: 'run test -- --watch=false --progress=false'
