# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  buildConfiguration: 'Release'
  solution: 'Proto.sln'
  packagejson: 'Proto.App/client-app'

jobs:
- job: dotnet
  pool: 'Default'
  steps:
  - checkout: self
    clean: 'true'
  - script: dotnet build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
    displayName: 'dotnet build $(buildConfiguration)'
  - task: DotNetCoreCLI@2
    displayName: 'Unit tests task'
    inputs:
      command: 'test'
      arguments: '--configuration $(buildConfiguration)'
      projects: '$(solution)'
      testRunTitle: 'Unit tests'
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: 'custom'
      workingDir: '$(packagejson)'
      customCommand: 'install'
  - task: Npm@1
    displayName: 'npm build'
    inputs:
      command: 'custom'
      workingDir: '$(packagejson)'
      customCommand: 'run build'
  - task: Npm@1
    displayName: 'npm test'
    inputs:
      command: 'custom'
      workingDir: '$(packagejson)'
      customCommand: 'run test -- --watch=false --progress=false'
  - task: CopyFiles@2
    inputs:
      SourceFolder: 'Proto.App/client-app/dist/client-app/'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/wwwroot'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
  
